blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/foXaCe/ha-ambeo_soundbar/blob/master/README.md
    about: Check the documentation first
  - name: Discussions
    url: https://github.com/foXaCe/ha-ambeo_soundbar/discussions
    about: Ask questions in discussions
